### PR TITLE
Changed TickLag

### PR DESCRIPTION
**Pull request by ImNotTraitor**
No idea what the fuck Im doing but I gotta learn somewhere, feel free to shit on me. I changed the ticklag to make the game feel more smoother.

### CODE REVIEW

**Comment by Cherkir** [comment]
What does that variable even do? It's not actually world.tick_lag

**Comment by Cherkir** [comment]
Also, the vast majority of lag is because the server has an extremely high CPU at this many players and tasks start hanging and everything gets backlogged

**Comment by Cherkir** [comment]
actually, this may help, merging

**Comment by ImNotTraitor** [comment]
Also if you have a config folder you'll have to change it in that.

**Pull request merged**
