### PR TITLE
Fixes Hub desc size

### PR DESCRIPTION
**Pull request by swordsith**
R e a l l y tho no. merge or lynch. /shrug -swordsith
This PR removes both the 100 text size and the "purple" span which didn't work for me at least. This contributes to me not wanting to kill myself if this is not merged the police will be called. thanks.

### CODE REVIEW

**Comment by Cherkir** [comment]
already changed

**Comment by swordsith** [comment]
Update is for left over shiz and added github also because for some reason it wasn't under world.dm but it is in the HUB

**Comment by swordsith** [comment]
really
image
still messed up on the hub

**Comment by Alexshreds** [comment]
Yeah, it's still huge

**Comment by Cherkir** [comment]
https://puu.sh/tOWGp/cf3d29bcac.png

strange, it's so much smaller on the website

byond ree

**Comment by swordsith** [comment]
use the byond client doof
just merger and i wont shoot :gun:

**Comment by Cherkir** [comment]
I wasn't aware that people actually used the byond client since it's a buggy piece of shit

oh well

**Comment by swordsith** [comment]
a really good amount of ss13 players do as you have to for alot of stuff

**Comment by Alexshreds** [comment]
I wouldn't know how much of a buggy piece of shit it is...

**Comment by Cherkir** [comment]
well, it seems like I have to do something about this, but I'd rather edit the update_status() code to give a better message if I can't make it YUUGE on the hub without it looking ugly on the pager

thanks TOM

**Comment by swordsith** [comment]
when the first pr gets ript' :cry:

**Pull request closed without merging**
