### PR TITLE
add's a config file under \isostation

### PR DESCRIPTION
**Pull request by swordsith**
Litterally add's a \config file for ease of testing, it wasn't there in
the first place for some reason, trust me merge and if you want to test
your code and have to make yourself the host you'll thank me :b:  #may
and or may not be stolen from para which may or may have not stolen it
from some other server.

### CODE REVIEW

**Comment by Cherkir** [comment]
wait what, this is already in

and you're in the example directory

**Comment by swordsith** [comment]
what

**Comment by swordsith** [comment]
and yeah I could take it out of the example directory but I'm too lazy.

**Comment by swordsith** [comment]
I cant find this anywhere else and when i added the config and put them under config from example it worked on a priv server so i could test stuff as host.

**Comment by Cherkir** [comment]
but the config directory is already there

**Comment by swordsith** [comment]
image
Where??

**Comment by swordsith** [comment]
Am I being stupid? i'm legit confused lmao.

**Comment by Cherkir** [comment]
seems that there was a .gitignore there from Eris code, nvm

**Comment by Cherkir** [comment]
I'm uploading all of the config stuff, so I'm just going to close this

**Comment by swordsith** [comment]
Well at least we got that cleared up and i'm not as blind as i thought i was for a second there.

**Pull request closed without merging**
